apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crave-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: crave-backend
                port:
                  number: 8000
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: crave-backend
                port:
                  number: 8000
          - path: /openapi.json
            pathType: Prefix
            backend:
              service:
                name: crave-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crave-frontend
                port:
                  number: 80
